# Generated by Django 3.2.9 on 2021-11-06 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('style', models.CharField(choices=[('algerian', 'Algerian Food'), ('arabic', 'Arabic Food'), ('asian', 'Asian Food'), ('american', 'American Food'), ('chinese', 'Chinese Food'), ('french', 'French Food'), ('japanese', 'Japanese Food'), ('italian', 'Italian Food'), ('greek', 'Greek Food'), ('spanish', 'Spanish Food'), ('mediterranean', 'Mediterranean Food'), ('lebanese', 'Lebanese Food'), ('moroccan', 'Moroccan Food'), ('turkish', 'Turkish Food'), ('thai', 'Thai Food'), ('indian', 'Indian Food'), ('cajun', 'Cajun Food'), ('mexican', 'Mexican Food'), ('caribbean', 'Caribbean Food'), ('german', 'German Food'), ('russian', 'Russian Food'), ('hungarian', 'Hungarian Food')], default='Arabic Food', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(blank=True, default='images/1.jpg', null=True, upload_to='')),
                ('ingredients', models.TextField(max_length=4000)),
                ('description', models.TextField(max_length=4000)),
                ('likes', models.DecimalField(decimal_places=0, default=0, max_digits=1000000)),
                ('dislikes', models.DecimalField(decimal_places=0, default=0, max_digits=1000000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('body', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='recipe.comment')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='recipe.recipe')),
            ],
        ),
    ]
