# Generated by Django 3.2.9 on 2021-12-03 19:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0006_auto_20211106_1631'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dislike',
            unique_together={('users', 'comment'), ('users', 'recipe')},
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('users', 'comment'), ('users', 'recipe')},
        ),
        migrations.AlterIndexTogether(
            name='dislike',
            index_together={('users', 'comment'), ('users', 'recipe')},
        ),
        migrations.AlterIndexTogether(
            name='like',
            index_together={('users', 'comment'), ('users', 'recipe')},
        ),
    ]
