# Generated by Django 3.2.9 on 2021-12-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profileuser_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='picture',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
