# Generated by Django 3.2.9 on 2021-12-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profileuser_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
